version: '3'

services:
    build-kernel:
        image: ghcr.io/stormbreaker-infrastructure/docker-stormci/kernel-build:latest
        container_name: kernel-buildsystem
        hostname: StormCI
        stdin_open: true